export type { WidthType } from './width'
export type { FontSizeType } from './fontSize'
export type { FontSize } from './fontSize'
export type { BreakpointType } from './breakpoints'
export { fontSizeToRem } from './fontSize'
export { mdScreen, smScreen } from './breakpoints'
